env: "maze___maze2d-large-v0"
term_fn: "no_termination"
reward_fn: "maze"
goal_proj_fn: "maze"
learned_rewards: false
num_steps: 200000
trial_length: 600

seed: 0
save_video: true

num_elites: 5
model_lr: 0.00028
model_wd: 0.00010
hidden_size: 200
model_batch_size: 512
validation_ratio: 0
freq_train_model: 600
patience: 12
num_epochs_train_model: 12
initial_exploration: 3000
checkpoint_model_every: 50000

planning_horizon: 30
cost_discount: 1.0
cost_aggregation: "sum_values"
cem_num_iters: 3
cem_elite_ratio: 0.01
cem_population_size: 400
cem_alpha: 0.1
cem_clipped_normal: false
cem_population_decay_factor: 1.0
cem_colored_noise_exponent: 3.0
cem_keep_elite_frac: 0.3

model_load_dir: null
grow_buffer: true
train_model: true
train_model_online: true
train_model_offline: false
offline_epochs: 0
offline_evaluate_every: 1
training_reward_fn: 'disagreement'
acting_module: null
eval_reward_fn: null
eval_reward_fns: [null]
eval_acting_modules: []

env_params:
  compact_goal_space: true
  fixed_start: true

additional_modules:

  disagreement: 
    _target_: mbrl.modules.DisagreementModule
    device: ${device}
    obs_dim: ???
    goal_dim: ???
    relevant_dims: []
    should_train_online: false
    should_train_offline: false
    normalize: true
    normalize_double_precision: true
